theme: jekyll-theme-cayman
title: A World Tour of Patent Analysis
description: Energy, FinTech & Artificial Intelligence at a glance
navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
    - GitHub Pages: "https://pages.github.com/"
  Author's home: "http://deanattali.com"
